[project]
name = "bound-datagen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "peft>=0.18.0",
    "runpod",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]

[project.scripts]
datagen = "datagen:main"
